# Generated by Django 4.2.20 on 2025-05-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Nationalities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.FloatField()),
                ('CapStatus', models.FloatField()),
                ('Innings', models.FloatField()),
                ('Runs', models.FloatField()),
                ('Balls', models.FloatField()),
                ('Average', models.FloatField()),
                ('SR', models.FloatField()),
                ('Fifites', models.FloatField()),
                ('hundreds', models.FloatField()),
                ('Fours', models.FloatField()),
                ('Sixes', models.FloatField()),
                ('Notout', models.FloatField()),
                ('PlayerRole', models.FloatField()),
                ('Class', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_info1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialism', models.FloatField()),
                ('Innings', models.FloatField()),
                ('Avg', models.FloatField()),
                ('SR', models.FloatField()),
                ('Fifties', models.FloatField()),
                ('Hundreds', models.FloatField()),
                ('Fours', models.FloatField()),
                ('Sixes', models.FloatField()),
                ('Runs', models.FloatField()),
                ('Balls', models.FloatField()),
                ('NotOuts', models.FloatField()),
                ('Class', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Sports',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserPredictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('label', models.CharField(default='data', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='player_photos/')),
                ('date_of_birth', models.DateField()),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nationalities')),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sports')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teams')),
            ],
        ),
    ]
