# Generated by Django 4.2.20 on 2025-05-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSportsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sport/')),
                ('label', models.CharField(default='data', max_length=20)),
            ],
        ),
    ]
